<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

defined('BASEPATH') OR exit('No direct script access allowed');


class Common {
    public $CI ;
    public function __construct() {
        $this->CI =& get_instance();
        
    }
    
    /*
     * @desc: will check the user is logged in or not
     * @params: session variable user_id
     * @output: if yes then redirect to dashboard module or signin module 
     */
    public function check_auth(){
        
        if(!$this->CI->session->has_userdata('user_id')):
            redirect('signin');
        
        endif;
        
    }
    
    
    
    /**
    * This function will return output in ajax call for alert to show
    * @param type $array
    */
    public function return_output($array = array()){
        echo json_encode($array);
        die();
    }

    
    
        /**
         * 
         * @param type $tableData  //tableddata for sorting and searching
         * @param type $table      //table id 
         * @param type $init_sql   //this variable will act as a primary sql if join or any other conditions are present
         * @return type array 
         */
        public function Table($tableData,$table,$init_sql = ""){
        
        $sql = "";
        $records_per_page = isset($tableData['rowCount'])? $tableData['rowCount']: 10;              //ger the records per page
        $current_page_number  = isset($tableData['current'])? $tableData['current'] : 1;            //get the current page if set
        
        $start_from = ($current_page_number - 1) * $records_per_page;                               //get the start from
        
        $sql .= ($init_sql != "")? $init_sql: "SELECT * FROM ".$table ." WHERE deleted = 0 " ;
        
        $order_by = '';
        if(isset($tableData["sort"]) && is_array($tableData["sort"]))
        {
            foreach($tableData["sort"] as $key => $value)
            {
             $order_by .= " $key $value, ";
            }
        }
        else
        {
            $sql .= ' ORDER BY '. $table .'.id ASC';
        }
        
        if($order_by != '')
        {
         $sql .= ' ORDER BY ' . substr($order_by, 0, -2);
        }
        if($records_per_page != -1)
        {
         $sql .= " LIMIT " . $start_from . ", " . $records_per_page;
        }
        
            $query = $this->CI->db->query($sql);
        return $query->result_array();
    }
    
    
    public function getIconsArray(){
        $iconsList = array(
            'crop-16-9' => 'crop-16-9',
            'filter-b-and-w' => 'filter-b-and-w',
            'power-setting' => 'power-setting',
            'power' => 'power',
            'swap-vertical-circle' => 'swap-vertical-circle',
            'collection-item-6' => 'collection-item-6',
            'phone-setting' => 'phone-setting',
            'reader' => 'reader',
            'tab-unselected' => 'tab-unselected',
            'collection-bookmark' => 'collection-bookmark',
            'money-box' => 'money-box',
            'camera-switch' => 'camera-switch',
            'globe' => 'globe',
            'comment-edit' => 'comment-edit',
            'flare' => 'flare',
            'format-underlined' => 'format-underlined',
            'lamp' => 'lamp',
            'space-bar' => 'space-bar',
            'input-composite' => 'input-composite',
            'badge-check' => 'badge-check',
            'airplane-off' => 'airplane-off',
            'airline-seat-recline-ex' => 'airline-seat-recline-ex',
            'wifi-off' => 'wifi-off',
            'plus' => 'plus',
            'block' => 'block',
            'border-all' => 'border-all',
            'border-color' => 'border-color',
            'image-o' => 'image-o',
            'hospital-alt' => 'hospital-alt',
            'hdr-weak' => 'hdr-weak',
            'google-old' => 'google-old',
            'vimeo' => 'vimeo',
            'collection-item-9-plus' => 'collection-item-9-plus',
            'outlook' => 'outlook',
            'account-add' => 'account-add',
            'pin-account' => 'pin-account',
            'collection-speaker' => 'collection-speaker',
            'rotate-ccw' => 'rotate-ccw',
            'devices-off' => 'devices-off',
            'format-line-spacing' => 'format-line-spacing',
            'flash' => 'flash',
            'collection-item' => 'collection-item',
            'replay' => 'replay',
            'battery-flash' => 'battery-flash',
            'caret-up-circle' => 'caret-up-circle',
            'google-maps' => 'google-maps',
            'chevron-up' => 'chevron-up',
            'smartphone-iphone' => 'smartphone-iphone',
            'assignment-check' => 'assignment-check',
            'view-toc' => 'view-toc',
            'balance' => 'balance',
            'grain' => 'grain',
            'border-bottom' => 'border-bottom',
            'phone-in-talk' => 'phone-in-talk',
            'yahoo' => 'yahoo',
            'male-alt' => 'male-alt',
            'twitch' => 'twitch',
            'lock-outline' => 'lock-outline',
            'lastfm' => 'lastfm',
            'card-membership' => 'card-membership',
            'settings' => 'settings',
            'keyboard-hide' => 'keyboard-hide',
            'view-module' => 'view-module',
            'reddit' => 'reddit',
            'equalizer' => 'equalizer',
            'lock-open' => 'lock-open',
            'gradient' => 'gradient',
            'store-24' => 'store-24',
            'audio' => 'audio',
            'camera-party-mode' => 'camera-party-mode',
            'input-svideo' => 'input-svideo',
            'phone-forwarded' => 'phone-forwarded',
            'star-half' => 'star-half',
            'toys' => 'toys',
            'tablet-mac' => 'tablet-mac',
            'blur-off' => 'blur-off',
            'format-indent-increase' => 'format-indent-increase',
            'iridescent' => 'iridescent',
            'alert-circle-o' => 'alert-circle-o',
            'comment-text' => 'comment-text',
            'paypal' => 'paypal',
            'plus-1' => 'plus-1',
            'leak-off' => 'leak-off',
            'labels' => 'labels',
            'videocam-switch' => 'videocam-switch',
            'alarm-snooze' => 'alarm-snooze',
            'truck' => 'truck',
            'search-in-file' => 'search-in-file',
            'n-6-square' => 'n-6-square',
            'flower' => 'flower',
            '8tracks' => '8tracks',
            'long-arrow-right' => 'long-arrow-right',
            'wifi' => 'wifi',
            'invert-colors-off' => 'invert-colors-off',
            'inbox' => 'inbox',
            'camera' => 'camera',
            'sort-asc' => 'sort-asc',
            'comment-list' => 'comment-list',
            'star-circle' => 'star-circle',
            'phone-sip' => 'phone-sip',
            'polymer' => 'polymer',
            'favorite-outline' => 'favorite-outline',
            'keyboard' => 'keyboard',
            'accounts' => 'accounts',
            'mail-reply' => 'mail-reply',
            'vk' => 'vk',
            'quote' => 'quote',
            'border-outer' => 'border-outer',
            'mic-setting' => 'mic-setting',
            'pocket' => 'pocket',
            'floppy' => 'floppy',
            'menu' => 'menu',
            'comment-alt-text' => 'comment-alt-text',
            'crop' => 'crop',
            'neg-2' => 'neg-2',
            'camera-bw' => 'camera-bw',
            'gps' => 'gps',
            'delete' => 'delete',
            'favorite' => 'favorite',
            'remote-control' => 'remote-control',
            'caret-right' => 'caret-right',
            'videocam-off' => 'videocam-off',
            'n-4-square' => 'n-4-square',
            'dialpad' => 'dialpad',
            'phone-locked' => 'phone-locked',
            'smartphone-info' => 'smartphone-info',
            'neg-1' => 'neg-1',
            'block-alt' => 'block-alt',
            'tv-play' => 'tv-play',
            'amazon' => 'amazon',
            'invert-colors' => 'invert-colors',
            'image' => 'image',
            'google-plus-box' => 'google-plus-box',
            'attachment-alt' => 'attachment-alt',
            'view-dashboard' => 'view-dashboard',
            'money-off' => 'money-off',
            'skip-previous' => 'skip-previous',
            'long-arrow-left' => 'long-arrow-left',
            'file-plus' => 'file-plus',
            'tab' => 'tab',
            'male-female' => 'male-female',
            'male' => 'male',
            'view-stream' => 'view-stream',
            'mic' => 'mic',
            'pin' => 'pin',
            'face' => 'face',
            'memory' => 'memory',
            'translate' => 'translate',
            'scissors' => 'scissors',
            'network-alert' => 'network-alert',
            'library' => 'library',
            'smartphone-ring' => 'smartphone-ring',
            'plus-2' => 'plus-2',
            'http' => 'http',
            'watch' => 'watch',
            'timer' => 'timer',
            'minus-square' => 'minus-square',
            'image-alt' => 'image-alt',
            'gps-dot' => 'gps-dot',
            'view-compact' => 'view-compact',
            'smartphone-download' => 'smartphone-download',
            'zoom-out' => 'zoom-out',
            'delicious' => 'delicious',
            'replay-30' => 'replay-30',
            'comment-image' => 'comment-image',
            'folder' => 'folder',
            'n-3-square' => 'n-3-square',
            'format-align-justify' => 'format-align-justify',
            'rotate-cw' => 'rotate-cw',
            'view-list-alt' => 'view-list-alt',
            'texture' => 'texture',
            'refresh-sync' => 'refresh-sync',
            'n-1-square' => 'n-1-square',
            'zero' => 'zero',
            'twitter' => 'twitter',
            'folder-star' => 'folder-star',
            'slideshare' => 'slideshare',
            'border-style' => 'border-style',
            'transform' => 'transform',
            'long-arrow-up' => 'long-arrow-up',
            'check-all' => 'check-all',
            'filter-center-focus' => 'filter-center-focus',
            'turning-sign' => 'turning-sign',
            'devices' => 'devices',
            'exposure-alt' => 'exposure-alt',
            'format-align-left' => 'format-align-left',
            'play-circle-outline' => 'play-circle-outline',
            'sort-desc' => 'sort-desc',
            'wifi-info' => 'wifi-info',
            'brightness-2' => 'brightness-2',
            'comment-text-alt' => 'comment-text-alt',
            'upload' => 'upload',
            'crop-7-5' => 'crop-7-5',
            'minus-circle' => 'minus-circle',
            'fast-forward' => 'fast-forward',
            'hourglass-alt' => 'hourglass-alt',
            'tumblr' => 'tumblr',
            'tablet-android' => 'tablet-android',
            'book-image' => 'book-image',
            'alert-polygon' => 'alert-polygon',
            'comment-alt' => 'comment-alt',
            'playlist-plus' => 'playlist-plus',
            'drink' => 'drink',
            'sun' => 'sun',
            'fullscreen' => 'fullscreen',
            'label' => 'label',
            'cloud-outline' => 'cloud-outline',
            'battery-alert' => 'battery-alert',
            'filter-tilt-shift' => 'filter-tilt-shift',
            'star' => 'star',
            'camera-front' => 'camera-front',
            'github-alt' => 'github-alt',
            'blogger' => 'blogger',
            'google' => 'google',
            'alarm-plus' => 'alarm-plus',
            'format-color-reset' => 'format-color-reset',
            'layers-off' => 'layers-off',
            'explicit' => 'explicit',
            'collection-plus' => 'collection-plus',
            'format-list-bulleted' => 'format-list-bulleted',
            'collection-image' => 'collection-image',
            'border-left' => 'border-left',
            'codepen' => 'codepen',
            'apps' => 'apps',
            'remote-control-alt' => 'remote-control-alt',
            'phone-paused' => 'phone-paused',
            'sec-3' => 'sec-3',
            'mic-outline' => 'mic-outline',
            'comment-outline' => 'comment-outline',
            'view-web' => 'view-web',
            'smartphone-setup' => 'smartphone-setup',
            'wrench' => 'wrench',
            'collection-item-5' => 'collection-item-5',
            'settings-square' => 'settings-square',
            'triangle-up' => 'triangle-up',
            'bookmark-outline' => 'bookmark-outline',
            'swap' => 'swap',
            'view-quilt' => 'view-quilt',
            'fast-rewind' => 'fast-rewind',
            'shuffle' => 'shuffle',
            'shield-check' => 'shield-check',
            'mall' => 'mall',
            'brightness-4' => 'brightness-4',
            'graduation-cap' => 'graduation-cap',
            'unfold-more' => 'unfold-more',
            'comment' => 'comment',
            'search-replace' => 'search-replace',
            'portable-wifi' => 'portable-wifi',
            'label-alt' => 'label-alt',
            'trending-flat' => 'trending-flat',
            'phone-missed' => 'phone-missed',
            'format-strikethrough-s' => 'format-strikethrough-s',
            'collection-item-8' => 'collection-item-8',
            'layers' => 'layers',
            'n-2-square' => 'n-2-square',
            'window-minimize' => 'window-minimize',
            'open-in-new' => 'open-in-new',
            'crop-landscape' => 'crop-landscape',
            'sec-10' => 'sec-10',
            'flickr' => 'flickr',
            'subway' => 'subway',
            'nature-people' => 'nature-people',
            'wifi-alt-2' => 'wifi-alt-2',
            'minus' => 'minus',
            'square-o' => 'square-o',
            'card' => 'card',
            'puzzle-piece' => 'puzzle-piece',
            'card-giftcard' => 'card-giftcard',
            'apple' => 'apple',
            'border-clear' => 'border-clear',
            'format-subject' => 'format-subject',
            'steam' => 'steam',
            'ticket-star' => 'ticket-star',
            'calendar-close' => 'calendar-close',
            'fullscreen-exit' => 'fullscreen-exit',
            'cloud-off' => 'cloud-off',
            'mood' => 'mood',
            'lock' => 'lock',
            'cloud-circle' => 'cloud-circle',
            'refresh' => 'refresh',
            'more' => 'more',
            'copy' => 'copy',
            'code-setting' => 'code-setting',
            'desktop-windows' => 'desktop-windows',
            'caret-down-circle' => 'caret-down-circle',
            'disc-full' => 'disc-full',
            'developer-board' => 'developer-board',
            'bluetooth-connected' => 'bluetooth-connected',
            'replay-10' => 'replay-10',
            'format-bold' => 'format-bold',
            'eject-alt' => 'eject-alt',
            'archive' => 'archive',
            'shopping-basket' => 'shopping-basket',
            'graphic-eq' => 'graphic-eq',
            'loupe' => 'loupe',
            'confirmation-number' => 'confirmation-number',
            'compass' => 'compass',
            'crop-3-2' => 'crop-3-2',
            'chevron-left' => 'chevron-left',
            'leak' => 'leak',
            'playstation' => 'playstation',
            'border-top' => 'border-top',
            'account' => 'account',
            'sign-in' => 'sign-in',
            'notifications-active' => 'notifications-active',
            'comment-more' => 'comment-more',
            'tune' => 'tune',
            'panorama-wide-angle' => 'panorama-wide-angle',
            'bus' => 'bus',
            'folder-star-alt' => 'folder-star-alt',
            'headset' => 'headset',
            'flip' => 'flip',
            'stackoverflow' => 'stackoverflow',
            'collection-item-4' => 'collection-item-4',
            'collection-pdf' => 'collection-pdf',
            'book' => 'book',
            'center-focus-weak' => 'center-focus-weak',
            'unfold-less' => 'unfold-less',
            'assignment-o' => 'assignment-o',
            'input-antenna' => 'input-antenna',
            'wrap-text' => 'wrap-text',
            'store' => 'store',
            'mail-send' => 'mail-send',
            'phone' => 'phone',
            'calendar-alt' => 'calendar-alt',
            'airplane' => 'airplane',
            'format-size' => 'format-size',
            'voicemail' => 'voicemail',
            'brightness-5' => 'brightness-5',
            'phone-ring' => 'phone-ring',
            'flash-off' => 'flash-off',
            'google-play' => 'google-play',
            'speaker' => 'speaker',
            'soundcloud' => 'soundcloud',
            'pause' => 'pause',
            'crop-square' => 'crop-square',
            'caret-left' => 'caret-left',
            'exposure' => 'exposure',
            'stop' => 'stop',
            'plus-circle-o' => 'plus-circle-o',
            'eye' => 'eye',
            'case-play' => 'case-play',
            'refresh-sync-alert' => 'refresh-sync-alert',
            'walk' => 'walk',
            'comment-alert' => 'comment-alert',
            'crop-5-4' => 'crop-5-4',
            'panorama-horizontal' => 'panorama-horizontal',
            'cast' => 'cast',
            'wifi-lock' => 'wifi-lock',
            'n-5-square' => 'n-5-square',
            'redo' => 'redo',
            'network-off' => 'network-off',
            'pin-assistant' => 'pin-assistant',
            'tv-alt-play' => 'tv-alt-play',
            'device-hub' => 'device-hub',
            'brightness-3' => 'brightness-3',
            'airline-seat-flat-angle' => 'airline-seat-flat-angle',
            'portable-wifi-off' => 'portable-wifi-off',
            'format-indent-decrease' => 'format-indent-decrease',
            'border-horizontal' => 'border-horizontal',
            'font' => 'font',
            'forward-30' => 'forward-30',
            'movie' => 'movie',
            'navigation' => 'navigation',
            'center-focus-strong' => 'center-focus-strong',
            'trending-up' => 'trending-up',
            'google-plus' => 'google-plus',
            'android-alt' => 'android-alt',
            'shield-security' => 'shield-security',
            '3d-rotation' => '3d-rotation',
            'sort-amount-desc' => 'sort-amount-desc',
            'hd' => 'hd',
            'tag-close' => 'tag-close',
            'landscape' => 'landscape',
            'dot-circle-alt' => 'dot-circle-alt',
            'time' => 'time',
            'circle' => 'circle',
            'format-color-fill' => 'format-color-fill',
            'trending-down' => 'trending-down',
            'caret-down' => 'caret-down',
            'gif' => 'gif',
            'group-work' => 'group-work',
            'storage' => 'storage',
            'gamepad' => 'gamepad',
            'hospital' => 'hospital',
            'smartphone' => 'smartphone',
            'grid-off' => 'grid-off',
            'videocam' => 'videocam',
            'caret-left-circle' => 'caret-left-circle',
            'arrow-missed' => 'arrow-missed',
            'more-vert' => 'more-vert',
            'accounts-add' => 'accounts-add',
            'blur-circular' => 'blur-circular',
            'collection-item-2' => 'collection-item-2',
            'text-format' => 'text-format',
            'airline-seat-legroom-ex' => 'airline-seat-legroom-ex',
            'screen-rotation-lock' => 'screen-rotation-lock',
            'accounts-alt' => 'accounts-alt',
            'arrow-right-top' => 'arrow-right-top',
            'surround-sound' => 'surround-sound',
            'language-python-alt' => 'language-python-alt',
            'view-list' => 'view-list',
            'cloud-box' => 'cloud-box',
            'info-outline' => 'info-outline',
            'plus-circle-o-duplicate' => 'plus-circle-o-duplicate',
            'vignette' => 'vignette',
            'volume-down' => 'volume-down',
            'laptop-mac' => 'laptop-mac',
            'cloud' => 'cloud',
            'flower-alt' => 'flower-alt',
            'email-open' => 'email-open',
            'airline-seat-recline-no' => 'airline-seat-recline-no',
            'skip-next' => 'skip-next',
            'airplay' => 'airplay',
            'flash-auto' => 'flash-auto',
            'portable-wifi-changes' => 'portable-wifi-changes',
            'view-carousel' => 'view-carousel',
            'calendar-check' => 'calendar-check',
            'city-alt' => 'city-alt',
            'language-html5' => 'language-html5',
            'format-clear' => 'format-clear',
            'palette' => 'palette',
            'hourglass' => 'hourglass',
            'shopping-cart' => 'shopping-cart',
            'thumb-up' => 'thumb-up',
            'notifications-none' => 'notifications-none',
            'map' => 'map',
            'nature' => 'nature',
            'photo-size-select-small' => 'photo-size-select-small',
            'skype' => 'skype',
            'eyedropper' => 'eyedropper',
            'forward-10' => 'forward-10',
            'filter-list' => 'filter-list',
            'globe-alt' => 'globe-alt',
            'eject' => 'eject',
            'thumb-up-down' => 'thumb-up-down',
            'wifi-outline' => 'wifi-outline',
            'plus-circle' => 'plus-circle',
            'check-circle' => 'check-circle',
            'view-headline' => 'view-headline',
            'case-check' => 'case-check',
            'bluetooth' => 'bluetooth',
            'hourglass-outline' => 'hourglass-outline',
            'toll' => 'toll',
            'language-javascript' => 'language-javascript',
            'airline-seat-flat' => 'airline-seat-flat',
            'arrows' => 'arrows',
            'chevron-down' => 'chevron-down',
            'movie-alt' => 'movie-alt',
            'cloud-download' => 'cloud-download',
            'spinner' => 'spinner',
            'play' => 'play',
            'key' => 'key',
            'hearing' => 'hearing',
            'hdr-off' => 'hdr-off',
            'search-for' => 'search-for',
            'facebook-box' => 'facebook-box',
            'format-list-numbered' => 'format-list-numbered',
            'time-restore-setting' => 'time-restore-setting',
            'phone-end' => 'phone-end',
            'airline-seat-individual' => 'airline-seat-individual',
            'account-o' => 'account-o',
            'tag-more' => 'tag-more',
            'account-box' => 'account-box',
            'dropbox' => 'dropbox',
            'account-box-mail' => 'account-box-mail',
            'tv' => 'tv',
            'format-align-center' => 'format-align-center',
            'check-square' => 'check-square',
            'twitter-box' => 'twitter-box',
            'file-text' => 'file-text',
            'help' => 'help',
            'collection-text' => 'collection-text',
            'card-sd' => 'card-sd',
            'looks' => 'looks',
            'notifications' => 'notifications',
            'bookmark' => 'bookmark',
            'alarm' => 'alarm',
            'hdr-strong' => 'hdr-strong',
            'scanner' => 'scanner',
            'card-off' => 'card-off',
            'flattr' => 'flattr',
            'pin-off' => 'pin-off',
            'windows' => 'windows',
            'blur' => 'blur',
            'download' => 'download',
            'close' => 'close',
            'collection-item-9' => 'collection-item-9',
            'volume-mute' => 'volume-mute',
            'closed-caption' => 'closed-caption',
            'comment-video' => 'comment-video',
            'tablet' => 'tablet',
            'account-box-phone' => 'account-box-phone',
            'swap-vertical' => 'swap-vertical',
            'compare' => 'compare',
            'rss' => 'rss',
            'crop-portrait' => 'crop-portrait',
            'car' => 'car',
            'flag' => 'flag',
            'collection-item-3' => 'collection-item-3',
            'collection-item-7' => 'collection-item-7',
            'cocktail' => 'cocktail',
            'city' => 'city',
            'format-clear-all' => 'format-clear-all',
            'accounts-list' => 'accounts-list',
            'shopping-cart-plus' => 'shopping-cart-plus',
            'notifications-paused' => 'notifications-paused',
            'phone-bluetooth' => 'phone-bluetooth',
            'arrow-left' => 'arrow-left',
            'pizza' => 'pizza',
            'camera-rear' => 'camera-rear',
            'format-valign-top' => 'format-valign-top',
            'gas-station' => 'gas-station',
            'wikipedia' => 'wikipedia',
            'github' => 'github',
            'alarm-off' => 'alarm-off',
            'card-travel' => 'card-travel',
            'assignment-return' => 'assignment-return',
            'collection-music' => 'collection-music',
            'google-glass' => 'google-glass',
            'bike' => 'bike',
            'bluetooth-off' => 'bluetooth-off',
            'assignment-account' => 'assignment-account',
            'instagram' => 'instagram',
            'phone-msg' => 'phone-msg',
            'format-ltr' => 'format-ltr',
            'dot-circle' => 'dot-circle',
            'shape' => 'shape',
            'email' => 'email',
            'code' => 'code',
            'border-vertical' => 'border-vertical',
            'view-agenda' => 'view-agenda',
            'pinterest-box' => 'pinterest-box',
            'nfc' => 'nfc',
            'github-box' => 'github-box',
            'select-all' => 'select-all',
            'hdr' => 'hdr',
            'camera-add' => 'camera-add',
            'timer-off' => 'timer-off',
            'run' => 'run',
            ' ungroup' => ' ungroup',
            'chart' => 'chart',
            'bug' => 'bug',
            'smartphone-landscape-lo' => 'smartphone-landscape-lo',
            'attachment' => 'attachment',
            'camera-roll' => 'camera-roll',
            'network-setting' => 'network-setting',
            'paypal-alt' => 'paypal-alt',
            'markunread-mailbox' => 'markunread-mailbox',
            'caret-up' => 'caret-up',
            'panorama-vertical' => 'panorama-vertical',
            'long-arrow-down' => 'long-arrow-down',
            'alarm-check' => 'alarm-check',
            'code-smartphone' => 'code-smartphone',
            'dns' => 'dns',
            'input-hdmi' => 'input-hdmi',
            'input-power' => 'input-power',
            'grid' => 'grid',
            'view-day' => 'view-day',
            'smartphone-lock' => 'smartphone-lock',
            'rotate-right' => 'rotate-right',
            'format-valign-center' => 'format-valign-center',
            'sort-amount-asc' => 'sort-amount-asc',
            'battery' => 'battery',
            '500px' => '500px',
            'share' => 'share',
            'triangle-down' => 'triangle-down',
            'eye-off' => 'eye-off',
            'tap-and-play' => 'tap-and-play',
            'cake' => 'cake',
            'broken-image' => 'broken-image',
            'mood-bad' => 'mood-bad',
            'ruler' => 'ruler',
            'cloud-outline-alt' => 'cloud-outline-alt',
            'chevron-right' => 'chevron-right',
            'brush' => 'brush',
            'format-valign-bottom' => 'format-valign-bottom',
            'functions' => 'functions',
            'coffee' => 'coffee',
            'assignment-returned' => 'assignment-returned',
            'collection-video' => 'collection-video',
            'roller' => 'roller',
            'pin-help' => 'pin-help',
            'info' => 'info',
            'radio' => 'radio',
            'airline-seat-legroom-re' => 'airline-seat-legroom-re',
            'car-wash' => 'car-wash',
            'card-sim' => 'card-sim',
            'youtube' => 'youtube',
            'washing-machine' => 'washing-machine',
            'link' => 'link',
            'comments' => 'comments',
            'view-week' => 'view-week',
            'undo' => 'undo',
            'caret-right-circle' => 'caret-right-circle',
            'headset-mic' => 'headset-mic',
            'smartphone-erase' => 'smartphone-erase',
            'star-outline' => 'star-outline',
            'alert-octagon' => 'alert-octagon',
            'pin-drop' => 'pin-drop',
            'mic-off' => 'mic-off',
            'square-down' => 'square-down',
            'vibration' => 'vibration',
            'money' => 'money',
            'forward' => 'forward',
            'folder-person' => 'folder-person',
            'plaster' => 'plaster',
            'refresh-alt' => 'refresh-alt',
            'view-comfy' => 'view-comfy',
            'photo-size-select-large' => 'photo-size-select-large',
            'label-alt-outline' => 'label-alt-outline',
            'usb' => 'usb',
            'account-circle' => 'account-circle',
            'arrow-merge' => 'arrow-merge',
            'wb-auto' => 'wb-auto',
            'square-right' => 'square-right',
            'brightness-7' => 'brightness-7',
            'edit' => 'edit',
            'hotel' => 'hotel',
            'format-rtl' => 'format-rtl',
            'pause-circle-outline' => 'pause-circle-outline',
            'xbox' => 'xbox',
            'repeat' => 'repeat',
            'group' => 'group',
            'calendar' => 'calendar',
            'linkedin-box' => 'linkedin-box',
            'notifications-off' => 'notifications-off',
            'screen-rotation' => 'screen-rotation',
            'smartphone-portrait-loc' => 'smartphone-portrait-loc',
            'window-maximize' => 'window-maximize',
            'flip-to-front' => 'flip-to-front',
            'format-align-right' => 'format-align-right',
            'smartphone-landscape' => 'smartphone-landscape',
            'blur-linear' => 'blur-linear',
            'home' => 'home',
            'cloud-upload' => 'cloud-upload',
            'behance' => 'behance',
            'railway' => 'railway',
            'gesture' => 'gesture',
            'crop-din' => 'crop-din',
            'account-calendar' => 'account-calendar',
            'arrow-right' => 'arrow-right',
            'gps-off' => 'gps-off',
            'dock' => 'dock',
            'minus-circle-outline' => 'minus-circle-outline',
            'google-pages' => 'google-pages',
            'network-outline' => 'network-outline',
            'smartphone-android' => 'smartphone-android',
            'forward-5' => 'forward-5',
            'view-subtitles' => 'view-subtitles',
            'flip-to-back' => 'flip-to-back',
            'print' => 'print',
            'receipt' => 'receipt',
            'mouse' => 'mouse',
            'desktop-mac' => 'desktop-mac',
            'airline-seat-legroom-no' => 'airline-seat-legroom-no',
            'chart-donut' => 'chart-donut',
            'check' => 'check',
            'collection-case-play' => 'collection-case-play',
            'smartphone-setting' => 'smartphone-setting',
            'volume-up' => 'volume-up',
            'flight-land' => 'flight-land',
            'widgets' => 'widgets',
            'crop-free' => 'crop-free',
            'whatsapp' => 'whatsapp',
            'playlist-audio' => 'playlist-audio',
            'wifi-alt' => 'wifi-alt',
            'steam-square' => 'steam-square',
            'present-to-all' => 'present-to-all',
            'notifications-add' => 'notifications-add',
            'network-locked' => 'network-locked',
            'play-circle' => 'play-circle',
            'disqus' => 'disqus',
            'border-right' => 'border-right',
            'youtube-play' => 'youtube-play',
            'google-drive' => 'google-drive',
            'globe-lock' => 'globe-lock',
            'balance-wallet' => 'balance-wallet',
            'cloud-done' => 'cloud-done',
            'tv-list' => 'tv-list',
            'pinterest' => 'pinterest',
            'linkedin' => 'linkedin',
            'case-download' => 'case-download',
            'google-earth' => 'google-earth',
            'file' => 'file',
            'camera-alt' => 'camera-alt',
            'view-array' => 'view-array',
            'format-italic' => 'format-italic',
            'check-circle-u' => 'check-circle-u',
            'wallpaper' => 'wallpaper',
            'power-input' => 'power-input',
            'brightness-auto' => 'brightness-auto',
            'search' => 'search',
            'replay-5' => 'replay-5',
            'dribbble' => 'dribbble',
            'search-in-page' => 'search-in-page',
            'arrow-left-bottom' => 'arrow-left-bottom',
            'close-circle' => 'close-circle',
            'assignment-alert' => 'assignment-alert',
            'fire' => 'fire',
            'router' => 'router',
            'filter-frames' => 'filter-frames',
            'format-color-text' => 'format-color-text',
            'rotate-left' => 'rotate-left',
            'aspect-ratio' => 'aspect-ratio',
            'parking' => 'parking',
            'alert-circle' => 'alert-circle',
            'format-strikethrough' => 'format-strikethrough',
            'language-python' => 'language-python',
            'zoom-in' => 'zoom-in',
            'bluetooth-search' => 'bluetooth-search',
            'account-box-o' => 'account-box-o',
            'tonality' => 'tonality',
            'network' => 'network',
            'border-inner' => 'border-inner',
            'accounts-outline' => 'accounts-outline',
            'time-countdown' => 'time-countdown',
            'label-heart' => 'label-heart',
            'tag' => 'tag',
            'album' => 'album',
            'collection-item-1' => 'collection-item-1',
            'brightness-setting' => 'brightness-setting',
            'cast-connected' => 'cast-connected',
            'facebook' => 'facebook',
            'help-outline' => 'help-outline',
            'evernote' => 'evernote',
            'card-alert' => 'card-alert',
            'android' => 'android',
            'car-taxi' => 'car-taxi',
            'picture-in-picture' => 'picture-in-picture',
            'arrow-split' => 'arrow-split',
            'traffic' => 'traffic',
            'spellcheck' => 'spellcheck',
            'repeat-one' => 'repeat-one',
            'alert-triangle' => 'alert-triangle',
            'boat' => 'boat',
            'accounts-list-alt' => 'accounts-list-alt',
            'satellite' => 'satellite',
            'volume-off' => 'volume-off',
            'view-column' => 'view-column',
            'circle-o' => 'circle-o',
            'bluetooth-setting' => 'bluetooth-setting',
            'mail-reply-all' => 'mail-reply-all',
            'refresh-sync-off' => 'refresh-sync-off',
            'time-restore' => 'time-restore',
            'long-arrow-return' => 'long-arrow-return',
            'plus-square' => 'plus-square',
            'case' => 'case',
            'folder-outline' => 'folder-outline',
            'close-circle-o' => 'close-circle-o',
            'time-interval' => 'time-interval',
            'flight-takeoff' => 'flight-takeoff',
            'assignment' => 'assignment',
            'brightness-6' => 'brightness-6',
            'laptop' => 'laptop',
            'hq' => 'hq',
            'odnoklassniki' => 'odnoklassniki',
            'swap-alt' => 'swap-alt',
            'cutlery' => 'cutlery',
            'laptop-chromebook' => 'laptop-chromebook',
            'language-css3' => 'language-css3',
            'camera-mic' => 'camera-mic',
            'slideshow' => 'slideshow',
            'battery-unknown' => 'battery-unknown',
            'fullscreen-alt' => 'fullscreen-alt',
            'collection-image-o' => 'collection-image-o',
            'seat' => 'seat',
            'collection-folder-image' => 'collection-folder-image',
            'window-restore' => 'window-restore',
            'thumb-down' => 'thumb-down',
            'open-in-browser' => 'open-in-browser',
            'female' => 'female',
            'pause-circle' => 'pause-circle',
            'play-for-work' => 'play-for-work',
            'calendar-note' => 'calendar-note',
            'long-arrow-tab' => 'long-arrow-tab',
            'aspect-ratio-al' => 'aspect-ratio-al'
        );
        
        return $iconsList;
    }
    
    /**
     * @desc placeholder image will create a placeholder image for user if the image is not uploaded by user.
     * @param type $string
     * @return type string img src
     */
    public function placeholder_image($string){
        $colors = '';
        for($o=1;$o<=3;$o++)
        {
            $colors .= str_pad( dechex( mt_rand( 100, 150 ) ), 2, '0', STR_PAD_LEFT);
        }
       

//        $k = array_rand($colors);
//        $v = $colors[$k];
        $url = 'https://via.placeholder.com/250/' . $colors. '/fff?text=';
        $str_to_array = explode(" ", $string);
        if (count($str_to_array) >= 2):
            $a = ucwords(substr("$str_to_array[0]", 0, 1));
            $b = ucwords(substr("$str_to_array[1]", 0, 1));
            return $url. $a . $b;
        elseif (count($str_to_array) == 1):
            return $url.ucwords(substr("$str_to_array[0]", 0, 1));
        endif;
    }


   
}